/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_voice_input_voiceInput_transcribe_parameter_0$schema = z.object({
  'b64': z.string(),
  'final': z.boolean(),
})
const _deepseek_ai_dsh_voice_input_voiceInput_transcribe_result$schema = z.object({
  'text': z.string(),
  'error': z.string().optional(),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-voice-input',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-voice-input#voiceInput/transcribe',
      service: 'voiceInput',
      namespace: 'voiceInput',
      method: 'transcribe',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-voice-input/types#VoiceTranscribeRequest',
            schema: _deepseek_ai_dsh_voice_input_voiceInput_transcribe_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-voice-input/types#VoiceTranscribeResult',
        schema: _deepseek_ai_dsh_voice_input_voiceInput_transcribe_result$schema,
      },
      sourceLocation: {"file":"packages/voice/voice-input/src/index.ts","line":101,"column":9},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
